#!/usr/bin/env python3
"""Turn captured terminal output into an SVG card for the README.

Every image in assets/ is generated by this, from real output captured by
tools/capture.sh. No mockups, no hand-drawn terminals, nothing that can drift
away from what the tool actually prints.

    python tools/terminal_svg.py session.txt assets/session.svg --title "substack push"
"""
import argparse
import html
import re
from pathlib import Path

BG = "#0d1117"
CHROME = "#161b22"
BORDER = "#30363d"
TEXT = "#c9d1d9"
DIM = "#6e7681"
GREEN = "#3fb950"
YELLOW = "#d29922"
RED = "#f85149"
CYAN = "#58a6ff"
MAGENTA = "#d2a8ff"
WHITE = "#f0f6fc"
DOTS = ("#ff5f57", "#febc2e", "#28c840")

FONT = ("ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, "
        "'DejaVu Sans Mono', monospace")
CHAR_W = 8.4
LINE_H = 21
FONT_SIZE = 14
PAD_X = 22
PAD_TOP = 52
PAD_BOTTOM = 20

KEYWORDS = [
    (re.compile(r"^(OK)(\s+)(.*)$"), GREEN),
    (re.compile(r"^(WARN)(\s+)(.*)$"), YELLOW),
    (re.compile(r"^(FAIL|error)(\s+)(.*)$"), RED),
]


def spans(line):
    """[(text, colour)] for one line."""
    if line.startswith("$ "):
        return [("$ ", GREEN), (line[2:], WHITE)]
    if line.startswith("> "):
        return [("> ", MAGENTA), (line[2:], WHITE)]
    stripped = line.lstrip()
    if stripped.startswith("$ "):
        pad = line[:len(line) - len(stripped)]
        return [(pad, DIM), ("$ ", GREEN), (stripped[2:], WHITE)]
    for pattern, colour in KEYWORDS:
        match = pattern.match(line)
        if match:
            return [(match.group(1), colour),
                    (match.group(2), TEXT),
                    (match.group(3), TEXT)]
    if line.startswith("# "):
        return [(line, DIM)]
    if line.startswith("    ") or line.startswith("  "):
        return [(line, DIM)]
    match = re.match(r"^([a-z][a-z ]{2,13})(\s\s+)(\S.*)$", line)
    if match:
        return [(match.group(1), DIM), (match.group(2), TEXT),
                (match.group(3), CYAN if "://" in match.group(3) else TEXT)]
    if re.match(r"^[A-Z ]+$", line.strip()) and line.strip():
        return [(line, WHITE)]
    return [(line, TEXT)]


def render(lines, title):
    width = max([len(line) for line in lines] + [len(title) + 12, 52])
    svg_w = int(width * CHAR_W + PAD_X * 2)
    svg_h = int(len(lines) * LINE_H + PAD_TOP + PAD_BOTTOM)

    out = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{svg_w}" height="{svg_h}" '
           f'viewBox="0 0 {svg_w} {svg_h}" role="img" '
           f'aria-label="Terminal session: {html.escape(title)}">']
    out.append(f'<rect width="{svg_w}" height="{svg_h}" rx="10" fill="{BG}" '
               f'stroke="{BORDER}"/>')
    out.append(f'<path d="M0 10a10 10 0 0 1 10-10h{svg_w - 20}a10 10 0 0 1 10 10v22H0z" '
               f'fill="{CHROME}"/>')
    out.append(f'<line x1="0" y1="32" x2="{svg_w}" y2="32" stroke="{BORDER}"/>')
    for index, colour in enumerate(DOTS):
        out.append(f'<circle cx="{18 + index * 18}" cy="16" r="5.5" fill="{colour}"/>')
    out.append(f'<text x="{svg_w / 2}" y="21" fill="{DIM}" font-size="12" '
               f'font-family="{FONT}" text-anchor="middle">{html.escape(title)}</text>')

    for row, line in enumerate(lines):
        y = PAD_TOP + row * LINE_H
        x = PAD_X
        for text, colour in spans(line):
            if not text:
                continue
            out.append(f'<text x="{x:.1f}" y="{y}" fill="{colour}" '
                       f'font-size="{FONT_SIZE}" font-family="{FONT}" '
                       f'xml:space="preserve">{html.escape(text)}</text>')
            x += len(text) * CHAR_W
    out.append("</svg>")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source")
    parser.add_argument("target")
    parser.add_argument("--title", default="substack")
    args = parser.parse_args()

    raw = Path(args.source).read_text(encoding="utf-8").replace("\t", "    ")
    lines = [line.rstrip() for line in raw.rstrip("\n").split("\n")]
    Path(args.target).parent.mkdir(parents=True, exist_ok=True)
    Path(args.target).write_text(render(lines, args.title), encoding="utf-8")
    print(f"wrote {args.target}  ({len(lines)} lines)")


if __name__ == "__main__":
    main()
